import Link from "next/link";

export const metadata = { title: "Terms" };

const EFFECTIVE_DATE = "May 16, 2026";

export default function TermsPage() {
  return (
    <div className="flex flex-1 flex-col">
      <main className="mx-auto w-full max-w-2xl flex-1 px-6 py-16 sm:py-24">
        <Link
          href="/"
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          ← Signal
        </Link>

        <article className="mt-8 space-y-8">
          <header className="space-y-2">
            <h1 className="text-3xl font-semibold tracking-tight">
              Terms of use
            </h1>
            <p className="text-sm text-muted-foreground">
              Effective {EFFECTIVE_DATE}
            </p>
          </header>

          <p className="text-base leading-relaxed">
            Signal is a personal project provided free of charge. By
            creating an account or using the app you agree to these terms.
            They are intentionally short and plainly worded.
          </p>

          <Section title="What Signal is">
            <p className="text-sm">
              Signal is a self-hosted financial intelligence tool. You enter
              your own financial activity and the app computes a Financial
              Health Score, detects patterns in your spending, and produces
              a short forecast. The numbers and patterns are calculated by
              deterministic code; the plain-English narrative on your
              dashboard is generated by a large language model from the same
              structured output.
            </p>
          </Section>

          <Section title="What Signal isn&rsquo;t">
            <p className="text-sm">
              Signal is <strong>not financial advice</strong>. It does not
              recommend specific products, allocations, debt strategies, or
              actions. It does not replace a qualified financial advisor,
              accountant, or tax professional. Treat its output as a
              starting point for your own thinking, not a directive.
            </p>
            <p className="mt-2 text-sm">
              Signal does not connect to your bank, move money, place
              trades, or take any action on your behalf. It only reads and
              writes data inside its own database.
            </p>
          </Section>

          <Section title="Your account">
            <p className="text-sm">
              You&apos;re responsible for the email address you sign up
              with, and for the accuracy of the data you enter. Magic-link
              authentication means anyone who can read your email inbox can
              sign in as you — treat that inbox accordingly.
            </p>
          </Section>

          <Section title="Acceptable use">
            <p className="text-sm">
              Don&apos;t use Signal to:
            </p>
            <ul className="ml-5 mt-1.5 list-disc space-y-1 text-sm">
              <li>Store data that isn&apos;t yours, or for which you lack permission to enter</li>
              <li>Probe, scrape, or attempt to bypass authentication or row-level security</li>
              <li>Submit content that is illegal, abusive, or designed to harm other users</li>
              <li>Resell access to the service or use it as part of a paid product without permission</li>
            </ul>
          </Section>

          <Section title="Provided &ldquo;as is&rdquo;">
            <p className="text-sm">
              Signal is provided as-is, without warranty of any kind.
              Although the code and engine logic are open and the math is
              deterministic, calculations may contain bugs, third-party
              dependencies may have outages, and the LLM-generated narrative
              may occasionally misread your situation. Verify anything
              before acting on it.
            </p>
          </Section>

          <Section title="Limitation of liability">
            <p className="text-sm">
              To the maximum extent permitted by law, the maintainer of
              Signal is not liable for any direct, indirect, incidental, or
              consequential damages arising from your use of the app —
              including (but not limited to) financial losses, missed
              opportunities, data inaccuracies, or service interruptions.
            </p>
          </Section>

          <Section title="Termination">
            <p className="text-sm">
              You can delete your account at any time from the{" "}
              <Link
                href="/settings"
                className="font-medium underline-offset-4 hover:underline"
              >
                settings page
              </Link>
              . The maintainer reserves the right to suspend or remove
              accounts that violate the acceptable-use section, or to
              shut the service down entirely with reasonable advance
              notice posted to the project repository.
            </p>
          </Section>

          <Section title="Changes">
            <p className="text-sm">
              These terms may be updated as the project evolves. Material
              changes will update the effective date at the top of this
              page and be announced in the{" "}
              <a
                href="https://github.com/joee-ks/signal"
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium underline-offset-4 hover:underline"
              >
                project repository
              </a>
              . Continued use of the app after a change constitutes
              acceptance.
            </p>
          </Section>

          <Section title="Contact">
            <p className="text-sm">
              Questions, concerns, or bug reports go to the{" "}
              <a
                href="https://github.com/joee-ks/signal/issues"
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium underline-offset-4 hover:underline"
              >
                project repository
              </a>
              .
            </p>
          </Section>
        </article>
      </main>

      <footer className="border-t">
        <div className="mx-auto flex w-full max-w-2xl flex-col items-center justify-between gap-3 px-6 py-6 text-xs text-muted-foreground sm:flex-row">
          <p>Signal provides information, not financial advice.</p>
          <div className="flex items-center gap-4">
            <Link href="/login" className="hover:text-foreground">
              Sign in
            </Link>
            <Link href="/privacy" className="hover:text-foreground">
              Privacy
            </Link>
            <Link href="/terms" className="hover:text-foreground">
              Terms
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-semibold tracking-tight">{title}</h2>
      {children}
    </section>
  );
}
